/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/workout-register` | `/workout-register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/program/big3` | `/program/big3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/program/bodyweight` | `/program/bodyweight`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/modal` | `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/workout-register` | `/workout-register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/program/big3` | `/program/big3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/program/bodyweight` | `/program/bodyweight`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/program` | `/program`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/records` | `/records`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/modal${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/workout-register${`?${string}` | `#${string}` | ''}` | `/workout-register${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/program/big3${`?${string}` | `#${string}` | ''}` | `/program/big3${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/program/bodyweight${`?${string}` | `#${string}` | ''}` | `/program/bodyweight${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/program${`?${string}` | `#${string}` | ''}` | `/program${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/records${`?${string}` | `#${string}` | ''}` | `/records${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout${`?${string}` | `#${string}` | ''}` | `/workout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/workout-register` | `/workout-register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/program/big3` | `/program/big3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/program/bodyweight` | `/program/bodyweight`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; };
    }
  }
}
